flowchart TD

    subgraph sg_Assum_Pricing["Assum_Pricing"]
        sect_Assum_Pricing_0["PRICING ASSUMPTIONS"]
        sect_Assum_Pricing_1["GROSS PRICE PER HL (AUD)"]
        sect_Assum_Pricing_2["Brand"]
        sect_Assum_Pricing_3["DISCOUNTS & REBATES"]
        sect_Assum_Pricing_4["EXCISE DUTY"]
        sect_Assum_Pricing_5["CALCULATED EXCISE PER HL:"]
        sect_Assum_Pricing_6["ANNUAL PRICE INCREASE"]
    end
    sect_Assum_Pricing_4 -- "Australia - Keg Rebate %, New Zealand - Rate per LAL (AUD equivalent)..." --> sect_Assum_Pricing_5
    ext_out_Calc_Revenue(["Calc_Revenue"])
    sect_Assum_Pricing_2 -- "AllDark, SkyBrew" --> ext_out_Calc_Revenue
    sect_Assum_Pricing_3 -- "Blended Off-Trade Discount, On-Trade Discount %" --> ext_out_Calc_Revenue
    sect_Assum_Pricing_5 -- "AU AllDark (6% ABV) - Keg, AU AllDark (6% ABV) - Standard..." --> ext_out_Calc_Revenue
    sect_Assum_Pricing_6 -- "Base Scenario, Downside Scenario" --> ext_out_Calc_Revenue