flowchart TD

    subgraph sg_Checks["Checks"]
        sect_Checks_0["MODEL INTEGRITY CHECKS"]
        sect_Checks_1["CHECK DESCRIPTION"]
    end
    ext_in_Assum_Finance(["Assum_Finance"])
    ext_in_Assum_Finance -- "Opening Retained Earnings" --> sect_Checks_1
    ext_in_Assum_Volume(["Assum_Volume"])
    ext_in_Assum_Volume -- "AllDark %, Australia %..." --> sect_Checks_1
    ext_in_BS(["BS"])
    ext_in_BS -- "Assets - Liabilities - Equity, Retained Earnings..." --> sect_Checks_1
    ext_in_CF(["CF"])
    ext_in_CF -- "Closing Cash, Dividends Paid" --> sect_Checks_1
    ext_in_Calc_Debt(["Calc_Debt"])
    ext_in_Calc_Debt -- "Total Debt" --> sect_Checks_1
    ext_in_Calc_Volume(["Calc_Volume"])
    ext_in_Calc_Volume -- "Total" --> sect_Checks_1
    ext_in_IS(["IS"])
    ext_in_IS -- "Gross Margin %, NET INCOME" --> sect_Checks_1