flowchart TD

    subgraph sg_Calc_Volume["Calc_Volume"]
        sect_Calc_Volume_0["VOLUME CALCULATIONS"]
        sect_Calc_Volume_1["TOTAL VOLUME (HL)"]
        sect_Calc_Volume_2["BY MARKET (HL)"]
        sect_Calc_Volume_3["BY CHANNEL (HL)"]
        sect_Calc_Volume_4["BY FORMAT (HL)"]
    end
    ext_in_Assum_Volume(["Assum_Volume"])
    ext_in_Assum_Volume -- "Apr, Aug..." --> sect_Calc_Volume_0
    ext_in_Assum_Volume -- "AllDark %, SkyBrew %..." --> sect_Calc_Volume_1
    ext_in_Assum_Volume -- "Australia %, New Zealand %" --> sect_Calc_Volume_2
    ext_in_Assum_Volume -- "Off-Trade %, On-Trade %" --> sect_Calc_Volume_3
    ext_in_Assum_Volume -- "Bottles %, Cans %..." --> sect_Calc_Volume_4
    ext_in_Control(["Control"])
    ext_in_Control -- "Active Scenario (1=Base, 2=Upside, 3=Downside)" --> sect_Calc_Volume_0
    sect_Calc_Volume_0 -- "Seasonality Index, CUMULATIVE GROWTH INDEX" --> sect_Calc_Volume_1
    sect_Calc_Volume_1 -- "Total" --> sect_Calc_Volume_2
    sect_Calc_Volume_1 -- "Total" --> sect_Calc_Volume_3
    sect_Calc_Volume_3 -- "On-Trade, Off-Trade" --> sect_Calc_Volume_4
    ext_out_Annual_Summary(["Annual_Summary"])
    sect_Calc_Volume_1 -- "Total" --> ext_out_Annual_Summary
    ext_out_BS(["BS"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_BS
    ext_out_CF(["CF"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_CF
    ext_out_Calc_COGS(["Calc_COGS"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_COGS
    sect_Calc_Volume_1 -- "Total" --> ext_out_Calc_COGS
    sect_Calc_Volume_4 -- "Bottles, Cans..." --> ext_out_Calc_COGS
    ext_out_Calc_Capex(["Calc_Capex"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_Capex
    sect_Calc_Volume_1 -- "Total" --> ext_out_Calc_Capex
    ext_out_Calc_Debt(["Calc_Debt"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_Debt
    ext_out_Calc_Opex(["Calc_Opex"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_Opex
    sect_Calc_Volume_1 -- "Total" --> ext_out_Calc_Opex
    sect_Calc_Volume_2 -- "Australia, New Zealand" --> ext_out_Calc_Opex
    sect_Calc_Volume_4 -- "Kegs" --> ext_out_Calc_Opex
    ext_out_Calc_Revenue(["Calc_Revenue"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_Revenue
    sect_Calc_Volume_1 -- "AllDark, SkyBrew..." --> ext_out_Calc_Revenue
    sect_Calc_Volume_2 -- "Australia, New Zealand" --> ext_out_Calc_Revenue
    ext_out_Calc_WC(["Calc_WC"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_Calc_WC
    ext_out_Checks(["Checks"])
    sect_Calc_Volume_1 -- "Total" --> ext_out_Checks
    ext_out_IS(["IS"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_IS
    ext_out_KPIs(["KPIs"])
    sect_Calc_Volume_0 -- "Date, Period" --> ext_out_KPIs
    sect_Calc_Volume_1 -- "Total" --> ext_out_KPIs