flowchart TD

    subgraph sg_Assum_Finance["Assum_Finance"]
        sect_Assum_Finance_0["FINANCING ASSUMPTIONS"]
        sect_Assum_Finance_1["EXISTING DEBT"]
        sect_Assum_Finance_2["REVOLVING FACILITY"]
        sect_Assum_Finance_3["EQUITY"]
        sect_Assum_Finance_4["DIVIDEND POLICY"]
        sect_Assum_Finance_5["CASH"]
    end
    ext_out_BS(["BS"])
    sect_Assum_Finance_1 -- "Term Loan - Annual Principal Payment" --> ext_out_BS
    sect_Assum_Finance_3 -- "Opening Retained Earnings, Opening Share Capital" --> ext_out_BS
    ext_out_CF(["CF"])
    sect_Assum_Finance_4 -- "Target Payout Ratio (% of Net Income)" --> ext_out_CF
    sect_Assum_Finance_5 -- "Opening Cash Balance" --> ext_out_CF
    ext_out_Calc_Debt(["Calc_Debt"])
    sect_Assum_Finance_1 -- "Term Loan - Annual Principal Payment, Term Loan - Interest Rate..." --> ext_out_Calc_Debt
    sect_Assum_Finance_2 -- "Commitment Fee (on undrawn), Current Drawn Amount..." --> ext_out_Calc_Debt
    ext_out_Checks(["Checks"])
    sect_Assum_Finance_3 -- "Opening Retained Earnings" --> ext_out_Checks