flowchart TD

    subgraph sg_Calc_Opex["Calc_Opex"]
        sect_Calc_Opex_0["OPERATING EXPENSES"]
        sect_Calc_Opex_1["LOGISTICS & DISTRIBUTION ($000s)"]
        sect_Calc_Opex_2["SG&A ($000s)"]
        sect_Calc_Opex_3["TOTAL OPEX ($000s)"]
    end
    ext_in_Assum_Costs(["Assum_Costs"])
    ext_in_Assum_Costs -- "Cold Chain Premium (Kegs), Domestic Freight - Australia..." --> sect_Calc_Opex_1
    ext_in_Assum_Costs -- "General & Admin, Marketing..." --> sect_Calc_Opex_2
    ext_in_Calc_COGS(["Calc_COGS"])
    ext_in_Calc_COGS -- "Cost Index (cumulative)" --> sect_Calc_Opex_1
    ext_in_Calc_Revenue(["Calc_Revenue"])
    ext_in_Calc_Revenue -- "Total Gross Revenue" --> sect_Calc_Opex_2
    ext_in_Calc_Volume(["Calc_Volume"])
    ext_in_Calc_Volume -- "Date, Period" --> sect_Calc_Opex_0
    ext_in_Calc_Volume -- "Australia, Kegs..." --> sect_Calc_Opex_1
    sect_Calc_Opex_1 -- "Total Logistics" --> sect_Calc_Opex_3
    sect_Calc_Opex_2 -- "Total SG&A" --> sect_Calc_Opex_3
    ext_out_Calc_WC(["Calc_WC"])
    sect_Calc_Opex_3 -- "Total Operating Expenses" --> ext_out_Calc_WC
    ext_out_IS(["IS"])
    sect_Calc_Opex_1 -- "Total Logistics" --> ext_out_IS
    sect_Calc_Opex_2 -- "General & Admin, Marketing..." --> ext_out_IS
    sect_Calc_Opex_3 -- "Total Operating Expenses" --> ext_out_IS