flowchart TD

    subgraph sg_Assum_Volume["Assum_Volume"]
        sect_Assum_Volume_0["VOLUME ASSUMPTIONS"]
        sect_Assum_Volume_1["BASE ANNUAL VOLUMES (HL) - YEAR 1"]
        sect_Assum_Volume_2["BRAND MIX"]
        sect_Assum_Volume_3["MARKET MIX"]
        sect_Assum_Volume_4["CHANNEL MIX"]
        sect_Assum_Volume_5["FORMAT MIX (within channel)"]
        sect_Assum_Volume_6["ANNUAL VOLUME GROWTH RATES"]
        sect_Assum_Volume_7["MONTHLY SEASONALITY INDEX"]
    end
    ext_out_Assum_WC(["Assum_WC"])
    sect_Assum_Volume_4 -- "Off-Trade %, On-Trade %" --> ext_out_Assum_WC
    ext_out_Calc_Revenue(["Calc_Revenue"])
    sect_Assum_Volume_2 -- "AllDark %, SkyBrew %" --> ext_out_Calc_Revenue
    sect_Assum_Volume_4 -- "Off-Trade %, On-Trade %" --> ext_out_Calc_Revenue
    sect_Assum_Volume_5 -- "Bottles %, Cans %..." --> ext_out_Calc_Revenue
    ext_out_Calc_Volume(["Calc_Volume"])
    sect_Assum_Volume_1 -- "Total Base Volume (HL)" --> ext_out_Calc_Volume
    sect_Assum_Volume_2 -- "AllDark %, SkyBrew %" --> ext_out_Calc_Volume
    sect_Assum_Volume_3 -- "Australia %, New Zealand %" --> ext_out_Calc_Volume
    sect_Assum_Volume_4 -- "Off-Trade %, On-Trade %" --> ext_out_Calc_Volume
    sect_Assum_Volume_5 -- "Bottles %, Cans %..." --> ext_out_Calc_Volume
    sect_Assum_Volume_6 -- "Year 1, Year 10" --> ext_out_Calc_Volume
    sect_Assum_Volume_7 -- "Apr, Aug..." --> ext_out_Calc_Volume
    ext_out_Checks(["Checks"])
    sect_Assum_Volume_2 -- "AllDark %, SkyBrew %" --> ext_out_Checks
    sect_Assum_Volume_3 -- "Australia %, New Zealand %" --> ext_out_Checks
    sect_Assum_Volume_4 -- "Off-Trade %, On-Trade %" --> ext_out_Checks
    sect_Assum_Volume_7 -- "Seasonality Check (should = 12)" --> ext_out_Checks