flowchart TD

    subgraph sg_Annual_Summary["Annual_Summary"]
        sect_Annual_Summary_0["ANNUAL SUMMARY"]
        sect_Annual_Summary_1["METRIC"]
    end
    ext_in_BS(["BS"])
    ext_in_BS -- "TOTAL EQUITY" --> sect_Annual_Summary_1
    ext_in_CF(["CF"])
    ext_in_CF -- "Cash from Operations, Closing Cash" --> sect_Annual_Summary_1
    ext_in_Calc_COGS(["Calc_COGS"])
    ext_in_Calc_COGS -- "Total COGS" --> sect_Annual_Summary_1
    ext_in_Calc_Capex(["Calc_Capex"])
    ext_in_Calc_Capex -- "Total Capex" --> sect_Annual_Summary_1
    ext_in_Calc_Debt(["Calc_Debt"])
    ext_in_Calc_Debt -- "Total Debt" --> sect_Annual_Summary_1
    ext_in_Calc_Revenue(["Calc_Revenue"])
    ext_in_Calc_Revenue -- "Net Revenue, Total Gross Revenue" --> sect_Annual_Summary_1
    ext_in_Calc_Volume(["Calc_Volume"])
    ext_in_Calc_Volume -- "Total" --> sect_Annual_Summary_1
    ext_in_IS(["IS"])
    ext_in_IS -- "EBIT, EBITDA..." --> sect_Annual_Summary_1