flowchart TD

    subgraph sg_KPIs["KPIs"]
        sect_KPIs_0["KEY PERFORMANCE INDICATORS"]
        sect_KPIs_1["VOLUME METRICS"]
        sect_KPIs_2["REVENUE METRICS"]
        sect_KPIs_3["PROFITABILITY METRICS"]
        sect_KPIs_4["CASH & LEVERAGE"]
        sect_KPIs_5["RETURNS"]
        sect_KPIs_6["WORKING CAPITAL"]
    end
    ext_in_Assum_WC(["Assum_WC"])
    ext_in_Assum_WC -- "Blended Average, Total Inventory Days..." --> sect_KPIs_6
    ext_in_BS(["BS"])
    ext_in_BS -- "TOTAL ASSETS, TOTAL EQUITY" --> sect_KPIs_5
    ext_in_CF(["CF"])
    ext_in_CF -- "Closing Cash" --> sect_KPIs_4
    ext_in_Calc_Capex(["Calc_Capex"])
    ext_in_Calc_Capex -- "Utilization %" --> sect_KPIs_1
    ext_in_Calc_Debt(["Calc_Debt"])
    ext_in_Calc_Debt -- "Total Debt, Total Interest Expense" --> sect_KPIs_4
    ext_in_Calc_Revenue(["Calc_Revenue"])
    ext_in_Calc_Revenue -- "Net Revenue, Total Gross Revenue" --> sect_KPIs_2
    ext_in_Calc_Volume(["Calc_Volume"])
    ext_in_Calc_Volume -- "Date, Period" --> sect_KPIs_0
    ext_in_Calc_Volume -- "Total" --> sect_KPIs_1
    ext_in_Calc_WC(["Calc_WC"])
    ext_in_Calc_WC -- "Net Working Capital" --> sect_KPIs_6
    ext_in_IS(["IS"])
    ext_in_IS -- "EBIT Margin %, EBITDA..." --> sect_KPIs_3
    ext_in_IS -- "EBITDA" --> sect_KPIs_4
    ext_in_IS -- "EBIT" --> sect_KPIs_5
    sect_KPIs_1 -- "Total Volume (HL)" --> sect_KPIs_2
    sect_KPIs_2 -- "Net Revenue ($000s)" --> sect_KPIs_6
    sect_KPIs_3 -- "Net Income ($000s)" --> sect_KPIs_5
    sect_KPIs_4 -- "Total Debt ($000s)" --> sect_KPIs_5