flowchart TD

    subgraph sg_BS["BS"]
        sect_BS_0["BALANCE SHEET"]
        sect_BS_1["ASSETS ($000s)"]
        sect_BS_2["Current Assets:"]
        sect_BS_3["Non-Current Assets:"]
        sect_BS_4["LIABILITIES ($000s)"]
        sect_BS_5["Current Liabilities:"]
        sect_BS_6["Non-Current Liabilities:"]
        sect_BS_7["EQUITY ($000s)"]
        sect_BS_8["BALANCE CHECK"]
    end
    ext_in_Assum_Finance(["Assum_Finance"])
    ext_in_Assum_Finance -- "Term Loan - Annual Principal Payment" --> sect_BS_5
    ext_in_Assum_Finance -- "Opening Retained Earnings, Opening Share Capital" --> sect_BS_7
    ext_in_CF(["CF"])
    ext_in_CF -- "Closing Cash" --> sect_BS_2
    ext_in_CF -- "Dividends Paid" --> sect_BS_7
    ext_in_Calc_Capex(["Calc_Capex"])
    ext_in_Calc_Capex -- "Net PP&E - Closing" --> sect_BS_3
    ext_in_Calc_Debt(["Calc_Debt"])
    ext_in_Calc_Debt -- "Closing Balance" --> sect_BS_5
    ext_in_Calc_Debt -- "Total Debt" --> sect_BS_6
    ext_in_Calc_Volume(["Calc_Volume"])
    ext_in_Calc_Volume -- "Date, Period" --> sect_BS_0
    ext_in_Calc_WC(["Calc_WC"])
    ext_in_Calc_WC -- "Prepayments, Total Inventory..." --> sect_BS_2
    ext_in_Calc_WC -- "Accruals, Trade Payables" --> sect_BS_5
    ext_in_IS(["IS"])
    ext_in_IS -- "NET INCOME" --> sect_BS_7
    sect_BS_2 -- "Total Current Assets" --> sect_BS_3
    sect_BS_3 -- "TOTAL ASSETS" --> sect_BS_8
    sect_BS_5 -- "Current Debt, Total Current Liabilities" --> sect_BS_6
    sect_BS_6 -- "TOTAL LIABILITIES" --> sect_BS_7
    sect_BS_7 -- "TOTAL LIABILITIES & EQUITY" --> sect_BS_8
    ext_out_Annual_Summary(["Annual_Summary"])
    sect_BS_7 -- "TOTAL EQUITY" --> ext_out_Annual_Summary
    ext_out_Checks(["Checks"])
    sect_BS_3 -- "TOTAL ASSETS" --> ext_out_Checks
    sect_BS_7 -- "Retained Earnings, TOTAL LIABILITIES & EQUITY" --> ext_out_Checks
    sect_BS_8 -- "Assets - Liabilities - Equity" --> ext_out_Checks
    ext_out_KPIs(["KPIs"])
    sect_BS_3 -- "TOTAL ASSETS" --> ext_out_KPIs
    sect_BS_7 -- "TOTAL EQUITY" --> ext_out_KPIs